### ISSUE TITLE
After a short amount of time the line items are not clickable anymore

### ISSUE THREAD

**Issue by bradphelan** [viacheslav-lozinskyi/MetaProject#1]
The metaproject window is displayed and the items are all correctly displayed 

![image](https://user-images.githubusercontent.com/17650/66997207-53214b00-f0d2-11e9-90f1-ca19dbcef4c8.png)

The goto source button does not function.
The goto description button works and opens a web pages. 

Closing visual studio and restarting and rebuilding doesn't seem to fix it. 

Sometimes the problem goes away and it starts working again only to stop working a short time later.

**Comment by viacheslav-lozinskyi** [comment]
Yesterday, was released new version of MetaProject (1.2.5).

In that release were implemented several new features, but several bugs were fixed too.
Possibly this bug is already fixed.
Please check it.

Thank you for your bug report, and sorry for that I didn't response on this issue earlier.

**Comment by viacheslav-lozinskyi** [comment]
In latest releases I can't reproduce it.
Could you write is this bug actual now?
