### ISSUE TITLE
For very long message lines find some UX improvements

### ISSUE THREAD

**Issue by bradphelan** [viacheslav-lozinskyi/MetaProject#11]
If I have a very long message line like

![image](https://user-images.githubusercontent.com/17650/107213781-3ddbd880-6a09-11eb-90ed-36cc527d2c23.png)

then when I put the mouse over it I get a huge tooltip the width of my 4k monitor

![image](https://user-images.githubusercontent.com/17650/107213832-50561200-6a09-11eb-9127-40d5f70cc8f6.png)

the tooltip has a timeout so I don't have time to read and understand the message before it disappears.

A few possible solutions which could be combined.

1.  Allow wrapping of messages in the table so tooltips are not necessary. 
2.  Disable the tooltip timeout 
3.  Ensure the tooltip window is not larger than the visual studio window. (Normally I have two applications side by side on a 4k monitor

![image](https://user-images.githubusercontent.com/17650/107214534-513b7380-6a0a-11eb-972a-fda7aad2176b.png)

4. When expanding with the *+* button the message is wrapped for easier understanding.

**Comment by viacheslav-lozinskyi** [comment]
Thanks for idea.

I thought also about this problem.
I also don't like existing tooltip, and will remake this functionality fully in one of the nearest release.

**Comment by viacheslav-lozinskyi** [comment]
This problem is solved in the last release (2.0.1).
Could you check it?
