### ISSUE TITLE
Clear all messages not working

### ISSUE THREAD

**Issue by FrankHeimes** [viacheslav-lozinskyi/MetaProject#13]
After loading a solution, the output filled with lots of messages:
![image](https://user-images.githubusercontent.com/20513035/113266903-0e916b80-92d6-11eb-85fb-6cd4509bf0ec.png)

After clicking the [X] Clear all messages button in the bottom right corner, only one of the lines vanished. The rest remained:
![image](https://user-images.githubusercontent.com/20513035/113266959-1a7d2d80-92d6-11eb-90c1-dccaf8b865c5.png)

**Comment by viacheslav-lozinskyi** [comment]
I see.

It is not a bug because those messages are pinned (icon on the right side of each message demonstrates it).
It means that they will not be deleted while they are pinned.
Those messages that you see it is "TODO" source. All those messages are always pinned. It normal behavior of this source.

**Comment by viacheslav-lozinskyi** [comment]
In next version of MetaProject I will change hint to this button which will be more relevant to expected behavior.

**Comment by FrankHeimes** [comment]
> Those messages that you see it is "TODO" source. All those messages are always pinned. It normal behavior of this source.

Thank you for clarifying.
It seems that I cannot unpin these messages.
This is unfortunate because most of them come from third-party code that I don't want to touch more than necessary.
Is there a "bulk" hide/show function; e.g. filter by expression "TODO: .*" and then hide all currently visible?

BTW.: The third line _TODO: add is..._ did disappear by clicking _Clear all messages_ even though it shouldn't have according to your explanation. It was pinned, too.

**Comment by viacheslav-lozinskyi** [comment]
You can hide "TODO" source (button on the right-bottom corner). In this case all todo messages will not be visible.

**Comment by viacheslav-lozinskyi** [comment]
Also you can hide concrete messages which you don't want to see.
