### ISSUE TITLE
Missing Xamarin for Visual Studio support

### ISSUE THREAD

**Issue by SoftArea-srl** [viacheslav-lozinskyi/MetaProject#3]
Following the discussion in the Q&A section, it is reported here the outcome. It seems that the debug output, generated by Xamarin during the debugging of Android/iOS solutions within Visual Studio 2019, is not captured by MetaProject. This is important if MetaProject is willing to also support mobile App developers working with Visual Studio/Xamarin.

**Comment by viacheslav-lozinskyi** [comment]
Thank you for the bug report. I will fix it ASAP.

**Comment by viacheslav-lozinskyi** [comment]
In the latest release of MetaProject (1.3.4) this bug is fixed.
Will be great to see your confirmation of it.
