### ISSUE TITLE
Disable VS' default 'Output' window globally

### ISSUE THREAD

**Issue by felikcat** [viacheslav-lozinskyi/MetaProject#6]
![devenv_V819I2Kwlv](https://user-images.githubusercontent.com/29991266/85987352-60e9d880-b9a2-11ea-92b7-f475a36fd643.png)
This option doesn't exist for CMake, so the 'Output' window still pops up automatically during CMake cache generation.

**Comment by viacheslav-lozinskyi** [comment]
I can't fix it, because it is not related to MetaProject.

**Comment by viacheslav-lozinskyi** [comment]
Right place for this bug is [here](https://developercommunity.visualstudio.com/topics/Known+Issue+in%3A+Visual+Studio+2019+Version+16.0.html)

**Comment by felikcat** [comment]
https://developercommunity.visualstudio.com/idea/1095295/add-show-output-window-when-cmake-cache-generation.html
For future reference.

**Comment by viacheslav-lozinskyi** [comment]
Thank you
