### ISSUE TITLE
Large context menu icons

### ISSUE THREAD

**Issue by x-santiaga-x** [viacheslav-lozinskyi/MetaProject#8]
There are large context menu icons in two resent releases.

![1](https://user-images.githubusercontent.com/37975005/91018468-4d509c00-e5f8-11ea-9d65-5afa6c3543a4.png)

**Comment by viacheslav-lozinskyi** [comment]
Thank you for the information.
I will fix it ASAP, and this fix will be in the nearest release.

**Comment by viacheslav-lozinskyi** [comment]
Fixed in current release 1.5.2.97.
Could you confirm that problem is solved?
