### ISSUE TITLE
Language other than Engilish not correctly shown

### ISSUE THREAD

**Issue by robin88chen** [viacheslav-lozinskyi/MetaProject#9]
![IM_2020-10-13-15-02-37](https://user-images.githubusercontent.com/28798593/95826718-5131ac80-0d65-11eb-9ca5-a0b5fd4e3cb3.png)

In the preview list, only English characters shown. But at the bottom line, whole message are correctly shown.

**Comment by viacheslav-lozinskyi** [comment]
Thank you for the information.
It will be fixed in the nearest release.

**Comment by viacheslav-lozinskyi** [comment]
Bug is fixed and available in MetaProject 1.5.5.102.
Could you check it?

**Comment by robin88chen** [comment]
It fixed. Thanks.
